%YAML:1.0
---
min_hsv: [ 8, 162, 0 ]
max_hsv: [ 43, 255, 255 ]
laplacian_threshold: 0
area_threshold: 51
morph_size: 4
width_reduction: 145
min_hist: 10
max_hist: 8000
percentile: 5.0000000000000000e-01
ip: "127.0.0.1"
port: 5060
